#!/usr/bin/env bash
# Generates the Codex agent TOMLs from the canonical personas in agents/*.md.
# Claude Code auto-discovers agents/, so only the Codex surface is generated.
# Output lives INSIDE the setup-team skill folder (skills/setup-team/codex-agents/)
# so it travels with the skill under every installer: `npx skills add` copies
# skill folders only, and a top-level dist/ never reached a Codex machine.
# /setup-team hands the human the copy command into the repo's .codex/agents/.
set -euo pipefail
cd "$(dirname "$0")/.."

out=skills/setup-team/codex-agents
mkdir -p "$out"
rm -f "$out"/*.toml

for md in agents/*.md; do
  role=$(basename "$md" .md)
  # frontmatter is the block between the first two '---' lines
  fm=$(awk 'NR==1 && $0!="---"{exit} NR>1 && $0=="---"{exit} NR>1{print}' "$md")
  body=$(awk 'BEGIN{n=0} $0=="---"{n++; next} n>=2{print}' "$md")
  name=$(printf '%s\n' "$fm" | sed -n 's/^name:[[:space:]]*//p' | head -1)
  description=$(printf '%s\n' "$fm" | sed -n 's/^description:[[:space:]]*//p' | head -1 | sed 's/^"\(.*\)"$/\1/; s/"/\\"/g')
  [ -n "$name" ] || { echo "$md: frontmatter has no name" >&2; exit 1; }
  [ -n "$description" ] || { echo "$md: frontmatter has no description" >&2; exit 1; }
  [ "$name" = "$role" ] || { echo "$md: name '$name' differs from file name '$role'" >&2; exit 1; }
  {
    echo "# Generated by scripts/build.sh from agents/$role.md. Edit the source, not this file."
    echo "name = \"$name\""
    echo "description = \"$description\""
    echo 'developer_instructions = """'
    printf '%s\n' "$body" | sed 's/"""/\\"\\"\\"/g'
    echo '"""'
  } > "$out/$role.toml"
  echo "wrote $out/$role.toml"
done
